const_value = 1

	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PIKACHU    ; 25
	const DEX_RAICHU     ; 26
	const DEX_SANDSHREW  ; 27
	const DEX_SANDSLASH  ; 28
	const DEX_NIDORAN_F  ; 29
	const DEX_NIDORINA   ; 30
	const DEX_NIDOQUEEN  ; 31
	const DEX_NIDORAN_M  ; 32
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_CLEFAIRY   ; 35
	const DEX_CLEFABLE   ; 36
	const DEX_VULPIX     ; 37
	const DEX_NINETALES  ; 38
	const DEX_JIGGLYPUFF ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_ZUBAT      ; 41
	const DEX_GOLBAT     ; 42
	const DEX_ODDISH     ; 43
	const DEX_GLOOM      ; 44
	const DEX_VILEPLUME  ; 45
	const DEX_PARAS      ; 46
	const DEX_PARASECT   ; 47
	const DEX_VENONAT    ; 48
	const DEX_VENOMOTH   ; 49
	const DEX_DIGLETT    ; 50
	const DEX_DUGTRIO    ; 51
	const DEX_MEOWTH     ; 52
	const DEX_PERSIAN    ; 53
	const DEX_PSYDUCK    ; 54
	const DEX_GOLDUCK    ; 55
	const DEX_MANKEY     ; 56
	const DEX_PRIMEAPE   ; 57
	const DEX_GROWLITHE  ; 58
	const DEX_ARCANINE   ; 59
	const DEX_POLIWAG    ; 60
	const DEX_POLIWHIRL  ; 61
	const DEX_POLIWRATH  ; 62
	const DEX_ABRA       ; 63
	const DEX_KADABRA    ; 64
	const DEX_ALAKAZAM   ; 65
	const DEX_MACHOP     ; 66
	const DEX_MACHOKE    ; 67
	const DEX_MACHAMP    ; 68
	const DEX_BELLSPROUT ; 69
	const DEX_WEEPINBELL ; 70
	const DEX_VICTREEBEL ; 71
	const DEX_TENTACOOL  ; 72
	const DEX_TENTACRUEL ; 73
	const DEX_GEODUDE    ; 74
	const DEX_GRAVELER   ; 75
	const DEX_GOLEM      ; 76
	const DEX_PONYTA     ; 77
	const DEX_RAPIDASH   ; 78
	const DEX_SLOWPOKE   ; 79
	const DEX_SLOWBRO    ; 80
	const DEX_MAGNEMITE  ; 81
	const DEX_MAGNETON   ; 82
	const DEX_FARFETCHD  ; 83
	const DEX_DODUO      ; 84
	const DEX_DODRIO     ; 85
	const DEX_SEEL       ; 86
	const DEX_DEWGONG    ; 87
	const DEX_GRIMER     ; 88
	const DEX_MUK        ; 89
	const DEX_SHELLDER   ; 90
	const DEX_CLOYSTER   ; 91
	const DEX_GASTLY     ; 92
	const DEX_HAUNTER    ; 93
	const DEX_GENGAR     ; 94
	const DEX_ONIX       ; 95
	const DEX_DROWZEE    ; 96
	const DEX_HYPNO      ; 97
	const DEX_KRABBY     ; 98
	const DEX_KINGLER    ; 99
	const DEX_VOLTORB    ; 100
	const DEX_ELECTRODE  ; 101
	const DEX_EXEGGCUTE  ; 102
	const DEX_EXEGGUTOR  ; 103
	const DEX_CUBONE     ; 104
	const DEX_MAROWAK    ; 105
	const DEX_HITMONLEE  ; 106
	const DEX_HITMONCHAN ; 107
	const DEX_LICKITUNG  ; 108
	const DEX_KOFFING    ; 109
	const DEX_WEEZING    ; 110
	const DEX_RHYHORN    ; 111
	const DEX_RHYDON     ; 112
	const DEX_CHANSEY    ; 113
	const DEX_TANGELA    ; 114
	const DEX_KANGASKHAN ; 115
	const DEX_HORSEA     ; 116
	const DEX_SEADRA     ; 117
	const DEX_GOLDEEN    ; 118
	const DEX_SEAKING    ; 119
	const DEX_STARYU     ; 120
	const DEX_STARMIE    ; 121
	const DEX_MR_MIME    ; 122
	const DEX_SCYTHER    ; 123
	const DEX_JYNX       ; 124
	const DEX_ELECTABUZZ ; 125
	const DEX_MAGMAR     ; 126
	const DEX_PINSIR     ; 127
	const DEX_TAUROS     ; 128
	const DEX_MAGIKARP   ; 129
	const DEX_GYARADOS   ; 130
	const DEX_LAPRAS     ; 131
	const DEX_DITTO      ; 132
	const DEX_EEVEE      ; 133
	const DEX_VAPOREON   ; 134
	const DEX_JOLTEON    ; 135
	const DEX_FLAREON    ; 136
	const DEX_PORYGON    ; 137
	const DEX_OMANYTE    ; 138
	const DEX_OMASTAR    ; 139
	const DEX_KABUTO     ; 140
	const DEX_KABUTOPS   ; 141
	const DEX_AERODACTYL ; 142
	const DEX_SNORLAX    ; 143
	const DEX_ARTICUNO   ; 144
	const DEX_ZAPDOS     ; 145
	const DEX_MOLTRES    ; 146
	const DEX_DRATINI    ; 147
	const DEX_DRAGONAIR  ; 148
	const DEX_DRAGONITE  ; 149
	const DEX_MEWTWO     ; 150
	const DEX_MEW        ; 151
	const DEX_ZMEOWTH     ; 152
	const DEX_ZPERSIAN    ; 153
	const DEX_ZPSYDUCK    ; 154
	const DEX_ZGOLDUCK    ; 155
	const DEX_ZMANKEY     ; 156
	const DEX_ZPRIMEAPE   ; 157
	const DEX_ZGROWLITHE  ; 158
	const DEX_ZARCANINE   ; 159
	const DEX_ZPOLIWAG    ; 160
	const DEX_ZPOLIWHIRL  ; 161
	const DEX_ZPOLIWRATH  ; 162
	const DEX_ZABRA       ; 163
	const DEX_ZKADABRA    ; 164
	const DEX_ZALAKAZAM   ; 165
	const DEX_ZMACHOP     ; 166
	const DEX_ZMACHOKE    ; 167
	const DEX_ZMACHAMP    ; 168
	const DEX_ZBELLSPROUT ; 169
	const DEX_ZWEEPINBELL ; 170
	const DEX_ZVICTREEBEL ; 171
	const DEX_ZTENTACOOL  ; 172
	const DEX_ZTENTACRUEL ; 173
	const DEX_ZGEODUDE    ; 174
	const DEX_ZGRAVELER   ; 175
	const DEX_ZGOLEM      ; 176
	const DEX_ZPONYTA     ; 177
	const DEX_ZRAPIDASH   ; 178
	const DEX_ZSLOWPOKE   ; 179
	const DEX_ZSLOWBRO    ; 180
	const DEX_ZMAGNEMITE  ; 181
	const DEX_ZMAGNETON   ; 182
	const DEX_ZFARFETCHD  ; 183
	const DEX_ZDODUO      ; 184
	const DEX_ZDODRIO     ; 185
	const DEX_ZSEEL       ; 186
	const DEX_ZDEWGONG    ; 187
	const DEX_ZGRIMER     ; 188
	const DEX_ZMUK        ; 189
	const DEX_ZSHELLDER   ; 190
	const DEX_ZCLOYSTER   ; 191
	const DEX_ZGASTLY     ; 192
	const DEX_ZHAUNTER    ; 193
	const DEX_ZGENGAR     ; 194
	const DEX_ZONIX       ; 195
	const DEX_ZDROWZEE    ; 196
	const DEX_ZHYPNO      ; 197
	const DEX_ZKRABBY     ; 198
	const DEX_ZKINGLER    ; 199
	const DEX_ZVOLTORB    ; 200
	const DEX_ZELECTRODE  ; 201
	const DEX_ZEXEGGCUTE  ; 202
	const DEX_ZEXEGGUTOR  ; 203
	const DEX_ZCUBONE     ; 204
	const DEX_ZMAROWAK    ; 205
	const DEX_ZHITMONLEE  ; 206
	const DEX_ZHITMONCHAN ; 207
	const DEX_ZLICKITUNG  ; 208
	const DEX_ZKOFFING    ; 209
	const DEX_ZWEEZING    ; 210
	const DEX_ZRHYHORN    ; 211
	const DEX_ZRHYDON     ; 212
	const DEX_ZCHANSEY    ; 213
	const DEX_ZTANGELA    ; 214
	const DEX_ZKANGASKHAN ; 215
	const DEX_ZHORSEA     ; 216
	const DEX_ZSEADRA     ; 217
	const DEX_ZGOLDEEN    ; 218
	const DEX_ZSEAKING    ; 219
	const DEX_ZSTARYU     ; 220
	const DEX_ZSTARMIE    ; 221
	const DEX_ZMR_MIME    ; 222
	const DEX_ZSCYTHER    ; 223
	const DEX_ZJYNX       ; 224
	const DEX_ZELECTABUZZ ; 225
	const DEX_ZMAGMAR     ; 226
	const DEX_ZPINSIR     ; 227
	const DEX_ZTAUROS     ; 228
	const DEX_ZMAGIKARP   ; 229
	const DEX_ZGYARADOS   ; 230
	const DEX_ZLAPRAS     ; 231
	const DEX_ZDITTO      ; 232
	const DEX_ZEEVEE      ; 233
	const DEX_ZVAPOREON   ; 234
	const DEX_ZJOLTEON    ; 235
	const DEX_ZFLAREON    ; 236
	const DEX_ZPORYGON    ; 237
	const DEX_ZOMANYTE    ; 238
	const DEX_ZOMASTAR    ; 239
	const DEX_ZKABUTO     ; 240
	const DEX_ZKABUTOPS   ; 241
	const DEX_ZAERODACTYL ; 242
	const DEX_ZSNORLAX    ; 243
	const DEX_ZARTICUNO   ; 244
	const DEX_ZZAPDOS     ; 245
	const DEX_ZMOLTRES    ; 246
	const DEX_ZDRATINI    ; 247
	const DEX_ZDRAGONAIR  ; 248 (248 is max for some reason)

NUM_POKEMON EQU const_value + -1
