MoveNames::
	db "POUND@"
	db "KARATE CHOP@"
	db "DOUBLESLAP@"
	db "COMET PUNCH@"
	db "MEGA PUNCH@"
	db "PAY DAY@"
	db "FIRE PUNCH@"
	db "ICE PUNCH@"
	db "THUNDERPUNCH@"
	db "SCRATCH@"
	db "VICEGRIP@"
	db "GUILLOTINE@"
	db "RAZOR WIND@"
	db "SWORDS DANCE@"
	db "CUT@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "FLY@"
	db "BIND@"
	db "SLAM@"
	db "VINE WHIP@"
	db "STOMP@"
	db "DOUBLE KICK@"
	db "MEGA KICK@"
	db "JUMP KICK@"
	db "ROLLING KICK@"
	db "SAND-ATTACK@"
	db "HEADBUTT@"
	db "HORN ATTACK@"
	db "FURY ATTACK@"
	db "HORN DRILL@"
	db "TACKLE@"
	db "BODY SLAM@"
	db "WRAP@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "TAIL WHIP@"
	db "POISON STING@"
	db "TWINEEDLE@"
	db "PIN MISSILE@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "SONICBOOM@"
	db "DISABLE@"
	db "ACID@"
	db "EMBER@"
	db "FLAMETHROWER@"
	db "MIST@"
	db "WATER GUN@"
	db "HYDRO PUMP@"
	db "SURF@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "BUBBLEBEAM@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "SUBMISSION@"
	db "LOW KICK@"
	db "COUNTER@"
	db "SEISMIC TOSS@"
	db "STRENGTH@"
	db "ABSORB@"
	db "MEGA DRAIN@"
	db "LEECH SEED@"
	db "GROWTH@"
	db "RAZOR LEAF@"
	db "SOLARBEAM@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "SLEEP POWDER@"
	db "PETAL DANCE@"
	db "STRING SHOT@"
	db "DRAGON RAGE@"
	db "FIRE SPIN@"
	db "THUNDERSHOCK@"
	db "THUNDERBOLT@"
	db "THUNDER WAVE@"
	db "THUNDER@"
	db "ROCK THROW@"
	db "EARTHQUAKE@"
	db "FISSURE@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "PSYCHIC@"
	db "HYPNOSIS@"
	db "MEDITATE@"
	db "AGILITY@"
	db "QUICK ATTACK@"
	db "RAGE@"
	db "TELEPORT@"
	db "NIGHT SHADE@"
	db "MIMIC@"
	db "SCREECH@"
	db "DOUBLE TEAM@"
	db "RECOVER@"
	db "HARDEN@"
	db "MINIMIZE@"
	db "SMOKESCREEN@"
	db "CONFUSE RAY@"
	db "WITHDRAW@"
	db "DEFENSE CURL@"
	db "BARRIER@"
	db "LIGHT SCREEN@"
	db "HAZE@"
	db "REFLECT@"
	db "FOCUS ENERGY@"
	db "BIDE@"
	db "METRONOME@"
	db "MIRROR MOVE@"
	db "SELFDESTRUCT@"
	db "EGG BOMB@"
	db "LICK@"
	db "SMOG@"
	db "SLUDGE@"
	db "BONE CLUB@"
	db "FIRE BLAST@"
	db "WATERFALL@"
	db "CLAMP@"
	db "SWIFT@"
	db "SKULL BASH@"
	db "SPIKE CANNON@"
	db "CONSTRICT@"
	db "AMNESIA@"
	db "KINESIS@"
	db "SOFTBOILED@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "DREAM EATER@"
	db "POISON GAS@"
	db "BARRAGE@"
	db "LEECH LIFE@"
	db "LOVELY KISS@"
	db "SKY ATTACK@"
	db "TRANSFORM@"
	db "BUBBLE@"
	db "DIZZY PUNCH@"
	db "SPORE@"
	db "FLASH@"
	db "PSYWAVE@"
	db "SPLASH@"
	db "ACID ARMOR@"
	db "CRABHAMMER@"
	db "EXPLOSION@"
	db "FURY SWIPES@"
	db "BONEMERANG@"
	db "REST@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "TRI ATTACK@"
	db "SUPER FANG@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "STRUGGLE@"
	db "ZOUND@"
	db "ZARATE CHOP@"
	db "ZOUBLESLAP@"
	db "ZOMET PUNCH@"
	db "ZEGA PUNCH@"
	db "ZAY DAY@"
	db "ZIRE PUNCH@"
	db "ZCE PUNCH@"
	db "ZHUNDERPUNCH@"
	db "ZCRATCH@"
	db "ZICEGRIP@"
	db "ZUILLOTINE@"
	db "ZAZOR WIND@"
	db "ZWORDS DANCE@"
	db "ZUT@"
	db "ZUST@"
	db "ZING ATTACK@"
	db "ZHIRLWIND@"
	db "ZLY@"
	db "ZIND@"
	db "ZLAM@"
	db "ZINE WHIP@"
	db "ZTOMP@"
	db "ZOUBLE KICK@"
	db "ZEGA KICK@"
	db "ZUMP KICK@"
	db "ZOLLING KICK@"
	db "ZAND-ATTACK@"
	db "ZEADBUTT@"
	db "ZORN ATTACK@"
	db "ZURY ATTACK@"
	db "ZORN DRILL@"
	db "ZACKLE@"
	db "ZODY SLAM@"
	db "ZRAP@"
	db "ZAKE DOWN@"
	db "ZHRASH@"
	db "ZOUBLE-EDGE@"
	db "ZAIL WHIP@"
	db "ZOISON STING@"
	db "ZWINEEDLE@"
	db "ZIN MISSILE@"
	db "ZEER@"
	db "ZITE@"
	db "ZROWL@"
	db "ZOAR@"
	db "ZING@"
	db "ZUPERSONIC@"
	db "ZONICBOOM@"
	db "ZISABLE@"
	db "ZCID@"
	db "ZMBER@"
	db "ZLAMETHROWER@"
	db "ZIST@"
	db "ZATER GUN@"
	db "ZYDRO PUMP@"
	db "ZURF@"
	db "ZCE BEAM@"
	db "ZLIZZARD@"
	db "ZSYBEAM@"
	db "ZUBBLEBEAM@"
	db "ZURORA BEAM@"
	db "ZYPER BEAM@"
	db "ZECK@"
	db "ZRILL PECK@"
	db "ZUBMISSION@"
	db "ZOW KICK@"
	db "ZOUNTER@"
	db "ZEISMIC TOSS@"
	db "ZTRENGTH@"
	db "ZBSORB@"
	db "ZEGA DRAIN@"
	db "ZEECH SEED@"
	db "ZROWTH@"
	db "ZAZOR LEAF@"
	db "ZOLARBEAM@"
	db "ZOISONPOWDER@"
	db "ZTUN SPORE@"
	db "ZLEEP POWDER@"
	db "ZETAL DANCE@"
	db "ZTRING SHOT@"
	db "ZRAGON RAGE@"
	db "ZIRE SPIN@"
	db "ZHUNDERSHOCK@"
	db "ZHUNDERBOLT@"

